export const INTERVIEW_FORM_FIELDS = [
  { key: 'fullName', label: 'Full name', placeholder: 'Your name', type: 'text', required: true },
  { key: 'discordName', label: 'Discord username', placeholder: 'name#0000 or @name', type: 'text', required: true },
  { key: 'age', label: 'Age', placeholder: '18', type: 'number', required: true },
  { key: 'country', label: 'Where are you from?', placeholder: 'Country / region', type: 'text', required: true },
  { key: 'hoursPerWeek', label: 'Hours per week on Drill UK', placeholder: '20', type: 'number', required: true },
];

export const INTERVIEW_LONG_FIELDS = [
  { key: 'priorBans', label: 'Have you ever been banned before?', placeholder: 'Explain any prior bans or say no.', required: true },
  { key: 'staffExperience', label: 'Previous staff experience', placeholder: 'Where have you staffed before, if anywhere?', required: true },
  { key: 'whyStaff', label: 'Why do you want to join staff?', placeholder: 'Explain why you want the role and what you would bring.', required: true },
  { key: 'whyDrill', label: 'Why Drill UK specifically?', placeholder: 'Why this server and not another one?', required: true },
];

export const DEFAULT_INTERVIEW_TEMPLATE = [
  {
    id: 'rules-major-rules',
    section: 'Rules & Situational Knowledge',
    question: 'Name 3 major rules from the server and explain why they exist.',
    maxScore: 5,
    sortOrder: 10,
    goodAnswerExample: 'Mentions RDM, NLR, Metagaming and explains each rule\'s importance.',
    badAnswerExample: 'Lists rules without meaning or gives wrong info.',
  },
  {
    id: 'rules-handle-nlr',
    section: 'Rules & Situational Knowledge',
    question: 'How would you handle someone breaking the NLR rule?',
    maxScore: 4,
    sortOrder: 20,
    goodAnswerExample: 'Warn, gather evidence, /report, escalate appropriately.',
    badAnswerExample: 'Just ban them or guesses what NLR is.',
  },
  {
    id: 'rules-threaten-ems',
    section: 'Rules & Situational Knowledge',
    question: 'If someone threatens EMS during RP, how should staff respond?',
    maxScore: 5,
    sortOrder: 30,
    goodAnswerExample: 'EMS are off-limits; enforce the rule after proper report process.',
    badAnswerExample: 'Says it is just RP or does not take it seriously.',
  },
  {
    id: 'rules-vdm-rdm-reports',
    section: 'Rules & Situational Knowledge',
    question: 'What is the correct way to handle reports involving VDM or RDM?',
    maxScore: 5,
    sortOrder: 40,
    goodAnswerExample: 'Check logs, gather clips, confirm with staff, follow protocol.',
    badAnswerExample: 'Says kick first or skips proof.',
  },
  {
    id: 'rules-command-abuse',
    section: 'Rules & Situational Knowledge',
    question: 'What do you do if you witness a player abusing /me or /ad commands?',
    maxScore: 3,
    sortOrder: 50,
    goodAnswerExample: 'Recognizes misuse and powergaming, documents and warns.',
    badAnswerExample: 'Shrugs it off or just tell them to stop.',
  },
  {
    id: 'rules-fear-rp',
    section: 'Rules & Situational Knowledge',
    question: 'What is FearRP and when must a player comply under it?',
    maxScore: 5,
    sortOrder: 60,
    goodAnswerExample: 'Explains that overwhelming threat means the player must comply and value life.',
    badAnswerExample: 'Says FearRP is optional or does not understand it.',
  },
  {
    id: 'rules-kos',
    section: 'Rules & Situational Knowledge',
    question: 'When is Kill On Sight (KOS) allowed on DRILL-UK?',
    maxScore: 3,
    sortOrder: 70,
    goodAnswerExample: 'Explains zone- and rules-based KOS allowances correctly.',
    badAnswerExample: 'Any time during beef or vague/confused.',
  },
  {
    id: 'rules-nlr-explain',
    section: 'Rules & Situational Knowledge',
    question: 'Explain the New Life Rule (NLR) and give an example of a violation.',
    maxScore: 5,
    sortOrder: 80,
    goodAnswerExample: 'Mentions memory loss, waiting period, and returning to the scene incorrectly.',
    badAnswerExample: 'Just do not respawn too fast or wrong logic.',
  },
  {
    id: 'rules-dv-me-abuse',
    section: 'Rules & Situational Knowledge',
    question: 'How should a staff member deal with a player abusing the /dv or /me command during an RP scene?',
    maxScore: 5,
    sortOrder: 90,
    goodAnswerExample: 'Explains rule misuse, gathers proof, follows staff protocol.',
    badAnswerExample: 'Says it is minor or shows lack of understanding.',
  },
  {
    id: 'rules-reporting-clips',
    section: 'Rules & Situational Knowledge',
    question: 'What are the rules for reporting a rule break and why are clips required?',
    maxScore: 4,
    sortOrder: 100,
    goodAnswerExample: 'Mentions /report, clip standards, and why clips are needed for proof.',
    badAnswerExample: 'No need for clips or does not know the process.',
  },
  {
    id: 'personality-motivation',
    section: 'Personality & Soft Skills',
    question: 'What motivates you to join the DRILL-UK staff team?',
    maxScore: 4,
    sortOrder: 110,
    goodAnswerExample: 'Wants to support the community, fairness, and RP quality.',
    badAnswerExample: 'Mentions power, revenge, or has no clear goal.',
  },
  {
    id: 'personality-conflict',
    section: 'Personality & Soft Skills',
    question: 'Describe a time you resolved a conflict or disagreement.',
    maxScore: 4,
    sortOrder: 120,
    goodAnswerExample: 'Describes a real conflict resolved calmly and fairly.',
    badAnswerExample: 'Blames others or gives no real example.',
  },
  {
    id: 'personality-friend-rulebreak',
    section: 'Personality & Soft Skills',
    question: 'How would you handle a friend breaking a serious server rule, for example Metagaming?',
    maxScore: 4,
    sortOrder: 130,
    goodAnswerExample: 'Would treat the friend equally and report or escalate if needed.',
    badAnswerExample: 'Lets the friend off or makes excuses.',
  },
  {
    id: 'personality-overwhelmed',
    section: 'Personality & Soft Skills',
    question: 'What do you do if you are overwhelmed or uncertain during a situation?',
    maxScore: 5,
    sortOrder: 140,
    goodAnswerExample: 'Would seek help, stay calm, and defer to higher staff when needed.',
    badAnswerExample: 'Panics, avoids responsibility, or asks no one for help.',
  },
  {
    id: 'personality-rude-player',
    section: 'Personality & Soft Skills',
    question: 'How do you maintain professionalism when a player is being rude?',
    maxScore: 5,
    sortOrder: 150,
    goodAnswerExample: 'Remain calm, avoid escalation, and follow procedure.',
    badAnswerExample: 'Gets aggressive or mutes without context.',
  },
  {
    id: 'commitment-hours',
    section: 'Commitment & Reliability',
    question: 'How many hours can you realistically commit per week to the server?',
    maxScore: 5,
    sortOrder: 160,
    goodAnswerExample: 'Provides realistic hours and commits to a schedule.',
    badAnswerExample: 'Overpromises or says whenever.',
  },
  {
    id: 'commitment-feedback',
    section: 'Commitment & Reliability',
    question: 'How do you feel about receiving constructive feedback?',
    maxScore: 4,
    sortOrder: 170,
    goodAnswerExample: 'Open to feedback and willing to improve.',
    badAnswerExample: 'Defensive or unwilling to accept critique.',
  },
  {
    id: 'commitment-break',
    section: 'Commitment & Reliability',
    question: 'What should you do if you need to take a break from your staff duties?',
    maxScore: 5,
    sortOrder: 180,
    goodAnswerExample: 'Would notify the team and use the proper leave process.',
    badAnswerExample: 'Ghosts or disappears without notice.',
  },
];

export function normalizeInterviewTemplate(items) {
  return [...(items || [])]
    .map((item, index) => ({
      id: item.id || `interview-question-${index + 1}`,
      section: item.section || 'General',
      question: item.question || '',
      maxScore: Number(item.maxScore || item.max_score || 5),
      sortOrder: Number(item.sortOrder || item.sort_order || (index + 1) * 10),
      goodAnswerExample: item.goodAnswerExample || item.good_answer_example || '',
      badAnswerExample: item.badAnswerExample || item.bad_answer_example || '',
      isActive: item.isActive === undefined ? (item.is_active === undefined ? true : Boolean(item.is_active)) : Boolean(item.isActive),
    }))
    .filter((item) => item.question)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}
